# Generated by Django 4.2.2 on 2023-06-17 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="elevator",
            old_name="is_moving",
            new_name="is_running",
        ),
        migrations.AddField(
            model_name="elevator",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="elevator",
            name="is_door_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="elevator",
            name="is_operational",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor", models.IntegerField()),
                (
                    "direction",
                    models.CharField(
                        choices=[("up", "Up"), ("down", "Down")], max_length=10
                    ),
                ),
                (
                    "elevators",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elevators",
                        to="home.elevator",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="elevator",
            name="requests",
            field=models.ManyToManyField(to="home.request"),
        ),
    ]
