# Generated by Django 4.2.2 on 2023-06-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_rename_is_moving_elevator_is_running_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elevator",
            name="requests",
        ),
    ]
